# NUMPY 

###  1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code to print the data types of both the variables.

Yes, there is a difference in the data type of the variables list_ and array_list. The elements in the list_ are strings, while the array_list is a NumPy array, and NumPy automatically infers the data type based on the elements.

In [1]:
import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_)

# Print data types
print("Data type of list_:", type(list_[0]))
print("Data type of array_list:", array_list.dtype)

Data type of list_: <class 'str'>
Data type of array_list: <U1


In this code, type(list_[0]) will give you the data type of the first element in the list, which is a string. array_list.dtype will give you the data type of the elements in the NumPy array, and it should be inferred as a string type as well since the elements in the original list are strings.

### 2. Write a code to print the data type of each and every element of both the variables list_ and array_list.

In [3]:
import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_)

# Print data types of each element in list_
print("Data types of elements in list_:")
for element in list_:
    print(type(element))

# Print data types of each element in array_list
print("\nData types of elements in array_list:")
for element in array_list:
    print(type(element))

Data types of elements in list_:
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>

Data types of elements in array_list:
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


### 3. Considering the following changes in the variable, array_list:

array_list = np.array(object = list_, dtype = int)

Will there be any difference in the data type of the elements present in both the variables, list_ and
arra_list? If so then print the data types of each and every element present in both the variables, list_
and arra_list.

Consider the below code to answer further questions:

import numpy as np

num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]

num_array = np.array(object = num_list)

Yes, there will be a difference in the data type of the elements between the variables list_ and array_list after the modification. When you specify the dtype parameter as int during the creation of array_list, it will force the conversion of the elements to integers.

In [5]:
import numpy as np

# Original list with string elements
list_ = ['1', '2', '3', '4', '5']

# Modified NumPy array with integer elements
array_list = np.array(object=list_, dtype=int)

# Print data types of each element in list_
print("Data types of elements in list_:")
for element in list_:
    print(type(element))

# Print data types of each element in array_list
print("\nData types of elements in array_list:")
for element in array_list:
    print(type(element))

Data types of elements in list_:
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>

Data types of elements in array_list:
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>


### 4. Q4. Write a code to find the following characteristics of variable, num_array:

(i)	 shape

(ii) size

In [6]:
import numpy as np

num_list = [[1, 2, 3], [4, 5, 6]]
num_array = np.array(object=num_list)

# (i) Find the shape of the array
shape_of_array = num_array.shape

# (ii) Find the size of the array
size_of_array = num_array.size

# Print the results
print("Shape of num_array:", shape_of_array)
print("Size of num_array:", size_of_array)

Shape of num_array: (2, 3)
Size of num_array: 6


### 5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array creation function.

In [8]:
import numpy as np

# Create a 3x3 matrix of zeros
zero_matrix = np.zeros((3, 3))

# Print the resulting matrix
print(zero_matrix)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


### 6. Create a identity matrix of shape 5*5 using numpy functions.

In [9]:
import numpy as np

# Create a 5x5 identity matrix
identity_matrix = np.eye(5)

# Print the resulting matrix
print(identity_matrix)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
